### ISSUE TITLE
Can't find referenced class when building with proguard

### ISSUE THREAD

**Issue by huishan** [emartech/android-mobile-engage-sdk#1]
Hi, we are facing issue building our app with the sdk when Proguard is enable. It was fine few days ago, we noticed it is failing since 2-3 days ago.

`Warning: com.emarsys.mobileengage.MobileEngageInternal: can't find referenced class com.emarsys.core.util.CoreJsonObject
Warning: com.emarsys.mobileengage.MobileEngageInternal: can't find referenced class com.emarsys.core.util.CoreJsonObject
...
Warning: there were 2 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)`

**Comment by stoto** [comment]
Hi huishan,

A fix was made in the newer versions of the SDK. Please update to get rid of the warning.
Sorry for the late answer.
